apiVersion: v1
kind: ConfigMap
metadata:
  name: write-config
  labels: 
    app: writefreely
data:
  config.ini: |
    [server]
    bind   = 0.0.0.0
    port   = 8080
    tls_cert_path = 
    tls_key_path  = 

    [database]
    type     = mysql
    username = root
    password = changeme
    database = writefreely
    host     = writedb-svc
    port     = 3306

    [app]
    site_name         = Write Freely Example Blog!
    host              = http://localhost:8080
    theme             = write
    disable_js        = false
    webfonts          = true
    single_user       = true
    open_registration = false
    min_username_len  = 3
    max_blogs         = 1
    federation        = true
    public_stats      = true
    private           = false
  
  MYSQL_DATABASE: writefreely
  MYSQL_ROOT_PASSWORD: changeme
    # MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=false  
    # db-data:/var/lib/mysql/data